sekoliko_dashboard:
    resource: "@AdminBundle/Resources/config/routing/dashboard.yml"
    prefix:   /

sekoliko_role:
    resource: "@AdminBundle/Resources/config/routing/role.yml"
    prefix:   /role

sekoliko_cms:
    resource: "@AdminBundle/Resources/config/routing/cms.yml"
    prefix:   /cms

sekoliko_jour_ferie:
    resource: "@AdminBundle/Resources/config/routing/jour_ferie.yml"
    prefix:   /jour-ferie

sekoliko_horaire:
    resource: "@AdminBundle/Resources/config/routing/horaire.yml"
    prefix:   /horaire

<<<<<<< HEAD
sekoliko_personnelle:
  resource: "@AdminBundle/Resources/config/routing/admin.yml"
  prefix:   /personnelle
=======
sekoliko_etablissement:
  resource: "@AdminBundle/Resources/config/routing/etablissement.yml"
  prefix:   /etablissement
>>>>>>> 46ca44504154836f2ef915e62d8cd203c95197d3
